# Generated by Django 4.2.6 on 2023-10-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('profileImage', models.CharField(max_length=100)),
            ],
        ),
    ]
