# Generated by Django 4.2.6 on 2023-10-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authors',
            new_name='author',
        ),
    ]
