# Generated by Django 4.2.6 on 2023-11-20 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_appuser_following_alter_appuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='following',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
