# Generated by Django 4.2.6 on 2023-11-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_appuser_github_appuser_host_appuser_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profileImage',
            field=models.URLField(blank=True, default=' https://imgur.com/t/default/pi2JlKR', null=True),
        ),
    ]
