# Generated by Django 4.2.6 on 2023-11-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_appuser_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
