# Generated by Django 4.2.6 on 2023-11-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_appuser_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='host',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='url',
        ),
    ]
