# Generated by Django 4.2.6 on 2023-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_remove_appuser_host_remove_appuser_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='id',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
