# Generated by Django 4.2.6 on 2023-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('author', 'follower')},
        ),
    ]
