# Generated by Django 4.2.6 on 2023-11-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_appuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='id',
        ),
    ]
