# Generated by Django 4.2.6 on 2023-11-16 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_remove_appuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
