# Generated by Django 4.2.6 on 2023-11-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_alter_follower_author_followrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='follower',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='author',
            new_name='object',
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('object', 'actor')},
        ),
    ]
