# Generated by Django 4.2.6 on 2023-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
