# Generated by Django 4.2.6 on 2023-11-23 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, editable=False, max_length=2048, null=True)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, editable=False, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, editable=False, max_length=2048, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='post', editable=False, max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=150, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('source', models.URLField(default='http://127.0.0.1:8000/', max_length=500)),
                ('origin', models.URLField(default='http://127.0.0.1:8000/', max_length=500)),
                ('contentType', models.CharField(default='text/plain', max_length=20)),
                ('visibility', models.CharField(default='PUBLIC', max_length=100)),
                ('unlisted', models.BooleanField()),
                ('url', models.URLField(editable=False, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('comments', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('likes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.like')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_post', to='posts.post'),
        ),
        migrations.AddField(
            model_name='category',
            name='linkedPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
