# Generated by Django 4.2.6 on 2023-11-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(editable=False, max_length=500, null=True),
        ),
    ]
