# Generated by Django 4.2.7 on 2023-12-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_foreign_comment_isforeign_like_foreign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(editable=False, max_length=500, null=True),
        ),
    ]
