# Generated by Django 4.2.6 on 2023-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
