# Generated by Django 4.2.6 on 2023-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_linkedpost_category_postid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='postId',
            new_name='linkedPost',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
