# Generated by Django 4.2.6 on 2023-11-23 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Follow', editable=False, max_length=6)),
                ('summary', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_request', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recieved_friend_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'object'), name='unique_request'),
        ),
    ]
