# Generated by Django 4.2.6 on 2023-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_friendrequest_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
